# Generated by Django 5.0.6 on 2024-06-03 06:00

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantite', models.IntegerField()),
                ('type_maintenance', models.CharField(choices=[('jour', 'Jour'), ('mois', 'Mois'), ('annee', 'Année')], max_length=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='machines_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('user_c_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fonction', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mon_application.user_c',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user_c',
            name='contact',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_c',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('admin', 'Administrateur')], default='user', max_length=10),
        ),
    ]
